# Generated by Django 3.2 on 2021-05-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20210520_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
