# Generated by Django 3.2 on 2021-05-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_instances'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instances',
            new_name='Instance',
        ),
    ]
