# Generated by Django 3.2 on 2021-05-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
