# Generated by Django 3.2 on 2021-05-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='user',
            name='features',
        ),
    ]
