# Generated by Django 3.2 on 2021-05-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_auto_20210523_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('diseases', models.CharField(max_length=10000)),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.instance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.user')),
            ],
        ),
    ]
