# Generated by Django 3.2 on 2021-05-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_auto_20210523_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nota',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
