# Generated by Django 3.2 on 2021-05-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0016_user_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consultas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
