# Generated by Django 3.2 on 2021-05-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0019_auto_20210530_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('probability', models.CharField(max_length=200)),
                ('diagnostic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.diagnostic')),
            ],
        ),
    ]
