# Generated by Django 3.2 on 2021-05-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0021_remove_diagnostic_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='alert',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
