# Generated by Django 3.2 on 2021-05-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0024_rename_references_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendartype',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
