# Generated by Django 3.2 on 2021-05-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0025_event_calendartype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
