# Generated by Django 3.2 on 2021-05-31 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0026_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='calendartype',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.patient'),
        ),
    ]
