# Generated by Django 3.2 on 2021-05-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0027_auto_20210531_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=200),
        ),
    ]
