# Generated by Django 3.2 on 2021-05-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0028_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='images/'),
        ),
    ]
