# Generated by Django 3.2 on 2021-06-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0031_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encryptid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
